### PR TITLE
Add numInstr bytes for Composite glyph with WE_HAVE_INSTRUCTIONS flag

### PR DESCRIPTION
**Pull request by anhngduc**
When flags & WE_HAVE_INSTRUCTIONS
then it will follow by
uint16 numInstr
uint8 instr[numInstr]
Ref:
https://learn.microsoft.com/en-us/typography/opentype/spec/glyf

### CODE REVIEW

**Comment by umanwizard** [comment]
Thanks, do you have an example of a .eot that fails to be decoded before this change?

**Comment by anhngduc** [comment]
Hi, I will check how to share the file.
Target font is Windows 10. "Calibri Bold Italic" font. After converting with original source and testing with ots-sanitize. The ots-sanitize shows an error like this
"WARNING: glyf: Bytecode length is bigger than maxp.maxsizeofInstructions %d"

**Comment by umanwizard** [comment]
You can e-mail the eot to me: brennan@umanwizard.com

**Comment by anhngduc** [comment]
Hello, how was it?

**Comment by umanwizard** [comment]
Hi @anhngduc , I did receive your e-mail, but I've been too busy to look at this. I'll look/test it this weekend and merge it if it looks okay.

**Comment by umanwizard** [comment]
Hi @anhngduc 

The first commit looks good.

But it seems you have several other commits with different fixes on the same branch. Can you open those as separate PRs and keep this branch to the WE_HAVE_INSTRUCTIONS issue?

**Comment by anhngduc** [comment]
Done.

**Pull request merged**
